name: Maven Test with H2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sapiblog

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for PostgreSQL to start
        run: |
          while ! pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL to start..."
            sleep 2
          done

      - name: Run SQL script to initialize the database
        run: |
          echo "Running SQL script to initialize the database"
          PGPASSWORD=postgres psql -h localhost -U postgres -d sapiblog -f src/test/resources/schema.sql

      - name: Run Maven tests
        run: mvn clean test
